language: php
php:
- 5.6
- hhvm
matrix:
  allow_failures:
  - php: hhvm
  fast_finish: true
before_script:
- composer self-update
- composer install --dev
- composer require satooshi/php-coveralls:* --dev
script:
- mkdir build/coverage
- phpunit
after_success:
- php vendor/bin/coveralls -v -c .coveralls.yml